In [1]:
# ----------------------------------
# DAY 3: NUMPY FOR DATA SCIENCE
# ----------------------------------

import numpy as np

print("🚀 Day 3: NumPy for Data Science 🚀\n")

# 1️⃣ Creating NumPy Arrays
print("== Creating NumPy Arrays ==")

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

print("Shape of arr1:", arr1.shape)
print("Shape of arr2:", arr2.shape)


# 2️⃣ Array Properties
print("\n== Array Properties ==")

print("Dimensions:", arr2.ndim)
print("Data Type:", arr1.dtype)
print("Total Elements:", arr2.size)


# 3️⃣ Creating Special Arrays
print("\n== Special Arrays ==")

zeros = np.zeros((3, 3))
ones = np.ones((2, 4))
identity = np.eye(3)
random_array = np.random.rand(3, 3)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)
print("Random Array:\n", random_array)


# 4️⃣ Indexing & Slicing
print("\n== Indexing & Slicing ==")

nums = np.array([10, 20, 30, 40, 50])

print("First element:", nums[0])
print("Last element:", nums[-1])
print("Sliced elements:", nums[1:4])

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Element at row 2 col 3:", matrix[1, 2])
print("First row:", matrix[0])
print("Second column:", matrix[:, 1])


# 5️⃣ Mathematical Operations
print("\n== Mathematical Operations ==")

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Power:", a ** 2)

print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Max:", np.max(a))
print("Min:", np.min(a))
print("Standard Deviation:", np.std(a))


# 6️⃣ Broadcasting
print("\n== Broadcasting ==")

data = np.array([10, 20, 30])
print("Original Data:", data)
print("After Adding 5:", data + 5)
print("After Multiplying by 2:", data * 2)


# 7️⃣ Boolean Indexing
print("\n== Boolean Indexing ==")

scores = np.array([45, 67, 89, 34, 90, 55])
passed = scores[scores >= 50]

print("All Scores:", scores)
print("Passed Scores:", passed)


# 8️⃣ Reshaping Arrays
print("\n== Reshaping Arrays ==")

nums2 = np.arange(1, 13)
reshaped = nums2.reshape(3, 4)

print("Original:", nums2)
print("Reshaped (3x4):\n", reshaped)


# 9️⃣ Mini Exercises
print("\n== Mini Exercises ==")

# Exercise 1: Create array from 1 to 20 and find even numbers
arr = np.arange(1, 21)
even_numbers = arr[arr % 2 == 0]
print("Even Numbers:", even_numbers)

# Exercise 2: Create random array and find mean
random_nums = np.random.randint(1, 100, size=10)
print("Random Numbers:", random_nums)
print("Mean:", np.mean(random_nums))

# Exercise 3: Normalize data (0 to 1 range)
data = np.array([10, 20, 30, 40, 50])
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Normalized Data:", normalized)

# Exercise 4: Matrix multiplication
mat1 = np.array([[1, 2],
                 [3, 4]])
mat2 = np.array([[5, 6],
                 [7, 8]])

result = np.dot(mat1, mat2)
print("Matrix Multiplication Result:\n", result)




🚀 Day 3: NumPy for Data Science 🚀

== Creating NumPy Arrays ==
1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape of arr1: (5,)
Shape of arr2: (2, 3)

== Array Properties ==
Dimensions: 2
Data Type: int64
Total Elements: 6

== Special Arrays ==
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Array:
 [[0.05046011 0.86312771 0.93314181]
 [0.36238881 0.47155687 0.08310467]
 [0.23776047 0.86192682 0.15975843]]

== Indexing & Slicing ==
First element: 10
Last element: 50
Sliced elements: [20 30 40]
Element at row 2 col 3: 6
First row: [1 2 3]
Second column: [2 5 8]

== Mathematical Operations ==
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Power: [1 4 9]
Sum: 6
Mean: 2.0
Max: 3
Min: 1
Standard Deviation: 0.816496580927726

== Broadcasting ==
Original Data: [10 20 30]
After Adding 5: [15 25 35]
After Multiplying by 2: [20 40 60]

== Boolea